language: node_js
cache:
  directories:
  - "~/.npm"
notifications:
  email: false
node_js:
- '10'
install: npm install
jobs:
  include:
    - stage: check
      script: npm run check-generate
    - stage: release
      node_js: 10
      script: npm run build
      before_deploy:
        - cd dist
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
      after_success:
      - sh .travis-push.sh