language: node_js
cache:
  directories:
  - "~/.npm"
notifications:
  email: false
node_js:
- '10'
before_install:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- git config --global push.default simple
- git remote set-url origin https://${GH_TOKEN}@github.com/vlaraort/npm-pact-binaries.git
install: npm install
jobs:
  include:
    - stage: check
      script: npm run check-generate
    - stage: release
      node_js: 10
      script: npm run build
      before_deploy:
        - cd dist
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
      after_deploy:
        - cd ..
        - branch_name=`git rev-parse --abbrev-ref HEAD`
        - git commit -am "[ci-skip] Update version"
        - git push origin $branch_name